update deps

diff --git a/.git-hooks/pre-commit b/.git-hooks/pre-commit
--- a/.git-hooks/pre-commit
+++ b/.git-hooks/pre-commit
@@ -1,22 +1,39 @@
 #!/bin/bash
 # https://dev.to/krzysztofkaczy9/do-you-really-need-husky-247b
 
-export PATH=$PATH:/usr/local/go/bin
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+YELLOW='\033[1;33m'
+NC='\033[0m' # No Color
 
-RED="\033[1;31m"
-GREEN="\033[1;32m"
-NC="\033[0m"
+function lint_ts {
+  staged_ts_files_array=$(git diff --cached --name-only --diff-filter=ACM | grep '\.ts$')
+  if [ -z "$staged_ts_files_array" ]; then
+    echo -e "${YELLOW}No TS files staged for commit.${NC}"
+    return
+  fi
+  staged_ts_files_array=$(echo "$staged_ts_files_array" | sed 's|^\/||')
 
-linter_exit_code=1
+  # convert array to list
+  staged_ts_files=""
+  for file in $staged_ts_files_array; do
+    staged_ts_files="$staged_ts_files $file"
+  done
+  staged_ts_files="${staged_ts_files# }"
 
-npx lint-staged
+  pnpm exec eslint --fix $staged_ts_files
+  pnpm exec prettier --write $staged_ts_files
 
-linter_exit_code=$?
-if [ $linter_exit_code -ne 0 ]
-then
-  echo "${RED} X Linter errors have occurred ${NC}"
-  exit 1
-else
-  echo "${GREEN} ✔ Linter didn't find any errors ${NC}"
-  exit 0
-fi
+  linter_exit_code=$?
+  if [ $linter_exit_code -ne 0 ]; then
+    echo -e "${RED}X eslint found issues. Commit aborted.${NC}"
+    exit 1
+  fi
+
+  # stage changes made by ESlint and Prettier
+  git diff --name-only --cached --diff-filter=ACM | grep '\.ts$' | xargs git add
+}
+
+lint_go
+lint_ts
+echo -e "${GREEN}✔ No issues found.${NC}"
